languageCode: "en-us"
title: "City of Philadelphia Digital Standards"
baseurl: "https://cityofphiladelphia.github.io/standards-docs/"
params:
  description: "Digital standards by the City of Philadelphia."
  heroImageLocation: "img/standards-hero.jpg"
theme: "phila.gov"
contentDir: "site-content"
disableKinds: ["RSS"]
