languageCode: "en-us"
title: "City of Philadelphia Digital Standards"
baseurl: "https://standards.phila.gov"
params:
  description: "Digtial standards by the City of Philadelphia."
theme: "phila.gov"
contentDir: "site-content"
